[package]
name = "sessionexec"
version = "0.7.2"
description = "Starts the user desktop environment of choice."
homepage = "https://github.com/NeroReflex/login_ng"
authors = ["Denis Benato <benato.denis96@gmail.com>"]
edition = "2021"
license-file = "../LICENSE.md"

[dependencies]
rust-ini = { version = "*" }
libc = { version = "*", features = [] }
whoami = { version = "*" }

[package.metadata.deb]
license-file = ["../LICENSE.md", "4"]
extended-description = """\
Starts the user desktop environment of choice."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/sessionexec", "usr/bin/", "755"],
    ["../rootfs/usr/lib/os-session-select", "usr/lib/", "755"],
    ["../rootfs/usr/lib/sessionexec/session-return.sh", "usr/lib/", "755"],
    ["../rootfs/usr/share/applications/org.sessionexec.session-return.desktop", "usr/share/applications/", "755"],
    ["../rootfs/usr/lib/login_ng-session/steamdeck.service", "usr/lib/login_ng-session/", "644"],
    ["../rootfs/usr/lib/login_ng-session/restart_session.service", "usr/lib/login_ng-session/", "644"],
]
