[profile.release]
lto = "fat"
# panic = "abort" # cargo-bitbake has problems with this
opt-level = 'z'
incremental = false
codegen-units = 1
strip = "debuginfo"

[workspace]
members = [
    "login_ng-session",
    "sessionexec"
]
resolver = "2"
